//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Legend.rc
//
#define IDB_A17                         17
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MYLegendTYPE                129
#define IDB_BACK                        130
#define IDB_BEGIN                       131
#define IDB_RULE                        132
#define IDD_PEOPLE                      134
#define IDD_NAME2                       135
#define IDD_NAME3                       136
#define IDD_NAME4                       137
#define IDD_signal                      138
#define IDB_A2                          140
#define IDB_A15                         140
#define IDB_A3                          141
#define IDB_A16                         141
#define IDB_A4                          142
#define IDB_A5                          143
#define IDB_A18                         143
#define IDB_A6                          144
#define IDB_A19                         144
#define IDB_A7                          145
#define IDB_A20                         145
#define IDB_A8                          146
#define IDB_A21                         146
#define IDB_A9                          147
#define IDB_A22                         147
#define IDB_A10                         148
#define IDB_A23                         148
#define IDB_AJ                          149
#define IDB_A24                         149
#define IDB_AQ                          150
#define IDB_A25                         150
#define IDB_AK                          151
#define IDB_A26                         151
#define IDB_H1                          152
#define IDB_H2                          153
#define IDB_H3                          154
#define IDB_H4                          155
#define IDB_H5                          156
#define IDB_H6                          157
#define IDB_H7                          158
#define IDB_H8                          159
#define IDB_H9                          160
#define IDB_H10                         161
#define IDB_HJ                          162
#define IDB_H11                         162
#define IDB_HQ                          163
#define IDB_H12                         163
#define IDB_HK                          164
#define IDB_H13                         164
#define IDB_M1                          166
#define IDB_M27                         166
#define IDB_M2                          167
#define IDB_M28                         167
#define IDB_M3                          168
#define IDB_M29                         168
#define IDB_M4                          169
#define IDB_M30                         169
#define IDB_M5                          170
#define IDB_M31                         170
#define IDB_M6                          171
#define IDB_M32                         171
#define IDB_M7                          172
#define IDB_M33                         172
#define IDB_M8                          173
#define IDB_M34                         173
#define IDB_M9                          174
#define IDB_M35                         174
#define IDB_M10                         175
#define IDB_M36                         175
#define IDB_MJ                          176
#define IDB_M37                         176
#define IDB_MQ                          177
#define IDB_M38                         177
#define IDB_MK                          178
#define IDB_M39                         178
#define IDB_K1                          179
#define IDB_K40                         179
#define IDB_K2                          180
#define IDB_K41                         180
#define IDB_K3                          181
#define IDB_K42                         181
#define IDB_K4                          182
#define IDB_K43                         182
#define IDB_K5                          183
#define IDB_K44                         183
#define IDB_K6                          184
#define IDB_K45                         184
#define IDB_K7                          185
#define IDB_K46                         185
#define IDB_K8                          186
#define IDB_K47                         186
#define IDB_K9                          187
#define IDB_K48                         187
#define IDB_K10                         188
#define IDB_K49                         188
#define IDB_KJ                          189
#define IDB_K50                         189
#define IDB_KQ                          190
#define IDB_K51                         190
#define IDB_A1                          191
#define IDB_A14                         191
#define IDB_KK                          192
#define IDB_K52                         192
#define IDR_WAVE1                       194
#define IDB_CARDBACK                    195
#define IDB_BITMAP1                     196
#define IDB_BITMAP2                     197
#define IDB_BITMAP3                     198
#define IDB_PLAYINGBACK                 199
#define IDB_P1                          200
#define IDB_P2                          201
#define IDB_P3                          202
#define IDB_P4                          203
#define IDB_P5                          204
#define IDC_TWO                         1000
#define IDC_THREE                       1001
#define IDC_FOUR                        1002
#define IDC_NAME2A                      1003
#define IDC_NAME2B                      1004
#define IDC_NAME3A                      1005
#define IDC_NAME3B                      1006
#define IDC_NAME3C                      1007
#define IDC_NAME4A                      1008
#define IDC_NAME4B                      1009
#define IDC_1                           1009
#define IDC_NAME4C                      1010
#define IDC_2                           1010
#define IDC_NAME4D                      1011
#define IDC_3                           1011
#define IDC_4                           1012
#define IDC_5                           1013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        205
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
